# Build File
cc_binary (
    name = 'hello_server',
    srcs = 'hello_server.cpp',
    deps = [
        '//idl:hello_thrift',
        '//boost:boost',
        '//thrift:thriftlibcpp',
        '//gflags:gflags'
    ],
)
