/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloService_H
#define HelloService_H

#include <thrift/TDispatchProcessor.h>
#include "hello_types.h"

namespace baidu { namespace longscheduler { namespace sample {

class HelloServiceIf {
 public:
  virtual ~HelloServiceIf() {}
  virtual void helloEcho(std::string& _return, const std::string& message, const HelloStruct& body) = 0;
  virtual void hello(const std::string& message, const HelloStruct& body) = 0;
};

class HelloServiceIfFactory {
 public:
  typedef HelloServiceIf Handler;

  virtual ~HelloServiceIfFactory() {}

  virtual HelloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloServiceIf* /* handler */) = 0;
};

class HelloServiceIfSingletonFactory : virtual public HelloServiceIfFactory {
 public:
  HelloServiceIfSingletonFactory(const boost::shared_ptr<HelloServiceIf>& iface) : iface_(iface) {}
  virtual ~HelloServiceIfSingletonFactory() {}

  virtual HelloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<HelloServiceIf> iface_;
};

class HelloServiceNull : virtual public HelloServiceIf {
 public:
  virtual ~HelloServiceNull() {}
  void helloEcho(std::string& /* _return */, const std::string& /* message */, const HelloStruct& /* body */) {
    return;
  }
  void hello(const std::string& /* message */, const HelloStruct& /* body */) {
    return;
  }
};


class HelloService_helloEcho_args {
 public:

  HelloService_helloEcho_args() : message() {
  }

  virtual ~HelloService_helloEcho_args() throw() {}

  std::string message;
  HelloStruct body;

  void __set_message(const std::string& val) {
    message = val;
  }

  void __set_body(const HelloStruct& val) {
    body = val;
  }

  bool operator == (const HelloService_helloEcho_args & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    if (!(body == rhs.body))
      return false;
    return true;
  }
  bool operator != (const HelloService_helloEcho_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloService_helloEcho_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloService_helloEcho_pargs {
 public:


  virtual ~HelloService_helloEcho_pargs() throw() {}

  const std::string* message;
  const HelloStruct* body;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloService_helloEcho_result__isset {
  _HelloService_helloEcho_result__isset() : success(false) {}
  bool success;
} _HelloService_helloEcho_result__isset;

class HelloService_helloEcho_result {
 public:

  HelloService_helloEcho_result() : success() {
  }

  virtual ~HelloService_helloEcho_result() throw() {}

  std::string success;

  _HelloService_helloEcho_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const HelloService_helloEcho_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloService_helloEcho_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloService_helloEcho_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloService_helloEcho_presult__isset {
  _HelloService_helloEcho_presult__isset() : success(false) {}
  bool success;
} _HelloService_helloEcho_presult__isset;

class HelloService_helloEcho_presult {
 public:


  virtual ~HelloService_helloEcho_presult() throw() {}

  std::string* success;

  _HelloService_helloEcho_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class HelloService_hello_args {
 public:

  HelloService_hello_args() : message() {
  }

  virtual ~HelloService_hello_args() throw() {}

  std::string message;
  HelloStruct body;

  void __set_message(const std::string& val) {
    message = val;
  }

  void __set_body(const HelloStruct& val) {
    body = val;
  }

  bool operator == (const HelloService_hello_args & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    if (!(body == rhs.body))
      return false;
    return true;
  }
  bool operator != (const HelloService_hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloService_hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloService_hello_pargs {
 public:


  virtual ~HelloService_hello_pargs() throw() {}

  const std::string* message;
  const HelloStruct* body;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class HelloServiceClient : virtual public HelloServiceIf {
 public:
  HelloServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  HelloServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void helloEcho(std::string& _return, const std::string& message, const HelloStruct& body);
  void send_helloEcho(const std::string& message, const HelloStruct& body);
  void recv_helloEcho(std::string& _return);
  void hello(const std::string& message, const HelloStruct& body);
  void send_hello(const std::string& message, const HelloStruct& body);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<HelloServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_helloEcho(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloServiceProcessor(boost::shared_ptr<HelloServiceIf> iface) :
    iface_(iface) {
    processMap_["helloEcho"] = &HelloServiceProcessor::process_helloEcho;
    processMap_["hello"] = &HelloServiceProcessor::process_hello;
  }

  virtual ~HelloServiceProcessor() {}
};

class HelloServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloServiceProcessorFactory(const ::boost::shared_ptr< HelloServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< HelloServiceIfFactory > handlerFactory_;
};

class HelloServiceMultiface : virtual public HelloServiceIf {
 public:
  HelloServiceMultiface(std::vector<boost::shared_ptr<HelloServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<HelloServiceIf> > ifaces_;
  HelloServiceMultiface() {}
  void add(boost::shared_ptr<HelloServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void helloEcho(std::string& _return, const std::string& message, const HelloStruct& body) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->helloEcho(_return, message, body);
    }
    ifaces_[i]->helloEcho(_return, message, body);
    return;
  }

  void hello(const std::string& message, const HelloStruct& body) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello(message, body);
    }
    ifaces_[i]->hello(message, body);
  }

};

}}} // namespace

#endif
