/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hello_constants.h"

namespace sample {

const helloConstants g_hello_constants;

helloConstants::helloConstants() {
  IDL_VERSION = "1.0.1";

}

} // namespace

